abstract: Perl extension to serve HTTP requests in POE.
author: Apocalypse <APOCAL@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-Server-SimpleHTTP
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  HTTP::Date: 0
  HTTP::Request: 0
  HTTP::Response: 0
  POE: 0.38
  Socket: 0
  Storable: 0
  Sys::Hostname: 0
version: 1.15
